-- Q. 
SELECT TIMEDIFF(i.DATETIME,o.DATETIME)
    FROM ANIMAL_INS i, ANIMAL_OUTS o;
    
    SELECT o.ANIMAL_ID, o.NAME
    FROM ANIMAL_OUTS o
    LEFT JOIN ANIMAL_INS i
        ON i.ANIMAL_ID = o.ANIMAL_ID
    ORDER BY i.DATETIEM - o.DATETIME